/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductId = IDL.Text;
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'razorpay' : IDL.Null,
  'card' : IDL.Null,
  'paytm' : IDL.Null,
});
export const OrderId = IDL.Text;
export const ProductType = IDL.Variant({
  'ebook' : IDL.Null,
  'course' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'productType' : ProductType,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'user' : IDL.Principal,
  'productId' : ProductId,
  'timestamp' : Time,
});
export const PaymentLinkConfig = IDL.Record({
  'url' : IDL.Opt(IDL.Text),
  'instructions' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([ProductId, PaymentMethod], [OrderId], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDownloadToken' : IDL.Func([OrderId], [IDL.Text], ['query']),
  'getDownloads' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getPaymentLink' : IDL.Func(
      [ProductId, PaymentMethod],
      [PaymentLinkConfig],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByType' : IDL.Func([ProductType], [IDL.Vec(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderAsPaid' : IDL.Func([OrderId], [], []),
  'setPaymentLink' : IDL.Func(
      [ProductId, PaymentMethod, PaymentLinkConfig],
      [],
      [],
    ),
  'validateDownloadToken' : IDL.Func([IDL.Text], [ProductId], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductId = IDL.Text;
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'razorpay' : IDL.Null,
    'card' : IDL.Null,
    'paytm' : IDL.Null,
  });
  const OrderId = IDL.Text;
  const ProductType = IDL.Variant({ 'ebook' : IDL.Null, 'course' : IDL.Null });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'productType' : ProductType,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'user' : IDL.Principal,
    'productId' : ProductId,
    'timestamp' : Time,
  });
  const PaymentLinkConfig = IDL.Record({
    'url' : IDL.Opt(IDL.Text),
    'instructions' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([ProductId, PaymentMethod], [OrderId], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDownloadToken' : IDL.Func([OrderId], [IDL.Text], ['query']),
    'getDownloads' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getPaymentLink' : IDL.Func(
        [ProductId, PaymentMethod],
        [PaymentLinkConfig],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByType' : IDL.Func(
        [ProductType],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderAsPaid' : IDL.Func([OrderId], [], []),
    'setPaymentLink' : IDL.Func(
        [ProductId, PaymentMethod, PaymentLinkConfig],
        [],
        [],
      ),
    'validateDownloadToken' : IDL.Func([IDL.Text], [ProductId], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };