/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'productId' : ProductId,
  'timestamp' : Time,
}
export type OrderId = string;
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null };
export interface PaymentLinkConfig {
  'url' : [] | [string],
  'instructions' : string,
}
export type PaymentMethod = { 'upi' : null } |
  { 'razorpay' : null } |
  { 'card' : null } |
  { 'paytm' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'productType' : ProductType,
  'image' : string,
  'price' : bigint,
}
export type ProductId = string;
export type ProductType = { 'ebook' : null } |
  { 'course' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[ProductId, PaymentMethod], OrderId>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDownloadToken' : ActorMethod<[OrderId], string>,
  'getDownloads' : ActorMethod<[[] | [Principal]], Array<Order>>,
  'getPaymentLink' : ActorMethod<[ProductId, PaymentMethod], PaymentLinkConfig>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByType' : ActorMethod<[ProductType], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderAsPaid' : ActorMethod<[OrderId], undefined>,
  'setPaymentLink' : ActorMethod<
    [ProductId, PaymentMethod, PaymentLinkConfig],
    undefined
  >,
  'validateDownloadToken' : ActorMethod<[string], ProductId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];